services:
  dns:
    image: "coredns/coredns:latest"
    ports:
      - "53:53/udp"
    volumes:
      - type: bind
        source: .
        target: /root
        read_only: true
    command: "-conf /root/Corefile"
    healthcheck:
        disable: true
